"""add unique constraint to propietario dni

Revision ID: 400106238e15
Revises: 6371e0cbe927
Create Date: 2026-07-22 10:16:01.254203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '400106238e15'
down_revision: Union[str, Sequence[str], None] = '6371e0cbe927'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_propietarios_dni', 'propietarios', ['dni'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_propietarios_dni', 'propietarios', type_='unique')
    # ### end Alembic commands ###
