"""add sesiones_invalidadas table

Revision ID: 535ee781aa89
Revises: b9a753ef61fe
Create Date: 2026-07-13 10:51:15.147559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '535ee781aa89'
down_revision: Union[str, Sequence[str], None] = 'b9a753ef61fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sesiones_invalidadas',
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('fecha_ultima_actividad', sa.DateTime(timezone=True), nullable=False),
    sa.Column('invalidado', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('jti')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sesiones_invalidadas')
    # ### end Alembic commands ###
