"""add motivo_consulta and timezone to citas fecha_hora

Revision ID: 6371e0cbe927
Revises: 535ee781aa89
Create Date: 2026-07-15 14:35:20.716004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6371e0cbe927'
down_revision: Union[str, Sequence[str], None] = '535ee781aa89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('citas', sa.Column('motivo_consulta', sa.String(length=255), nullable=False))
    op.alter_column('citas', 'fecha_hora',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('citas', 'fecha_hora',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('citas', 'motivo_consulta')
    # ### end Alembic commands ###
