"""esquema inicial: 7 tablas del ERD

Revision ID: 70a3171d0565
Revises: 
Create Date: 2026-07-09 14:10:51.650225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70a3171d0565'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('propietarios',
    sa.Column('id_propietario', sa.Integer(), nullable=False),
    sa.Column('dni', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=150), nullable=False),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id_propietario')
    )
    op.create_table('tratamientos',
    sa.Column('id_tratamiento', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('tipo_tratamiento', sa.Text(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('tarifa_por_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id_tratamiento')
    )
    op.create_table('veterinarios',
    sa.Column('id_veterinario', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('apellidos', sa.String(length=50), nullable=False),
    sa.Column('especialidad', sa.String(length=50), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id_veterinario')
    )
    op.create_table('mascotas',
    sa.Column('id_mascota', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('especie', sa.String(length=50), nullable=False),
    sa.Column('raza', sa.String(length=50), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('peso', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('id_propietario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_propietario'], ['propietarios.id_propietario'], ),
    sa.PrimaryKeyConstraint('id_mascota')
    )
    op.create_table('citas',
    sa.Column('id_cita', sa.Integer(), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('valor_consulta', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('diagnostico', sa.Text(), nullable=True),
    sa.Column('id_mascota', sa.Integer(), nullable=False),
    sa.Column('id_veterinario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_mascota'], ['mascotas.id_mascota'], ),
    sa.ForeignKeyConstraint(['id_veterinario'], ['veterinarios.id_veterinario'], ),
    sa.PrimaryKeyConstraint('id_cita')
    )
    op.create_table('citas_tratamientos',
    sa.Column('id_citas_tratamientos', sa.Integer(), nullable=False),
    sa.Column('id_tratamiento', sa.Integer(), nullable=False),
    sa.Column('id_cita', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('dosis', sa.String(length=100), nullable=False),
    sa.Column('seguimiento', sa.Text(), nullable=True),
    sa.Column('valor_tratamiento', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['id_cita'], ['citas.id_cita'], ),
    sa.ForeignKeyConstraint(['id_tratamiento'], ['tratamientos.id_tratamiento'], ),
    sa.PrimaryKeyConstraint('id_citas_tratamientos')
    )
    op.create_table('facturas',
    sa.Column('id_factura', sa.Integer(), nullable=False),
    sa.Column('id_cita', sa.Integer(), nullable=False),
    sa.Column('seguro', sa.String(length=100), nullable=True),
    sa.Column('forma_pago', sa.String(length=20), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('importe_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['id_cita'], ['citas.id_cita'], ),
    sa.PrimaryKeyConstraint('id_factura'),
    sa.UniqueConstraint('id_cita')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('facturas')
    op.drop_table('citas_tratamientos')
    op.drop_table('citas')
    op.drop_table('mascotas')
    op.drop_table('veterinarios')
    op.drop_table('tratamientos')
    op.drop_table('propietarios')
    # ### end Alembic commands ###
